spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: leobesho
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect






