package com.practice.day2.model;

import java.time.LocalDate;

public record AuthorResponseDTO(
        int authorId,           // Generated by DB - not in request
        String authorName,      // From request
        String nationality,     // From request
        LocalDate birthdate    // From entity (if you add it)

) {}